import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';
import { Unbounded } from 'next/font/google';

const unbounded = Unbounded({ 
  subsets: ['latin'], 
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`min-h-screen flex flex-col ${unbounded.className} bg-gradient-to-br from-purple-50 to-blue-50`}>
        <Header />
        <main className="flex-1 flex items-center justify-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
