import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Unbounded } from 'next/font/google';

const unbounded = Unbounded({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={unbounded.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
